version: '3'

tasks:

  # Build and run a debug container from local source code
  # Example: task run-local -- list
  run-local:
    cmd: >-
      docker build --progress=plain . -t cloudypad:local && 
      CLOUDYPAD_IMAGE="cloudypad:local" ./cloudypad.sh {{.CLI_ARGS}}

  run-local-no-build:
    cmd: >-
      CLOUDYPAD_IMAGE="cloudypad:local" ./cloudypad.sh {{.CLI_ARGS}}

  build:
    cmd: docker build . -t cloudypad:local

  # Generate Typescript Paperspace client from OpenAPI specifications
  paperspace-client-gen:
    vars:
      PAPERSPACE_OPENAPI_DIR: "src/providers/paperspace/client/openapi"
      PAPERSPACE_GENERATED_DIR: "src/providers/paperspace/client/generated-api"
    cmds:
    - curl https://api.paperspace.com/v1/openapi.json -o {{ .PAPERSPACE_OPENAPI_DIR }}/openapi.json

    # Filter only machine-related operations
    # Our client doesn't need the rest for now
    - >-
      cat {{ .PAPERSPACE_OPENAPI_DIR }}/openapi.json | jq '{ openapi, info, servers, components, externalDocs, paths: { 
        "/auth/session": .paths."/auth/session",
        "/machines": .paths."/machines",
        "/machines/{id}": .paths."/machines/{id}",
        "/machines/{id}/restart": .paths."/machines/{id}/restart",
        "/machines/{id}/start": .paths."/machines/{id}/start",
        "/machines/{id}/stop": .paths."/machines/{id}/stop",
      }}' > {{ .PAPERSPACE_OPENAPI_DIR }}/machines-only.json
    
    # # Cleanup old files before generation
    - rm -rf {{ .PAPERSPACE_GENERATED_DIR }} || true

    # Run generator
    - >- 
      podman run -it --rm -v $PWD:/local -w /local docker.io/openapitools/openapi-generator-cli:latest@sha256:6747991566e4c3e43a30d5982f21da08c1cad78e95093fab04f494687b341788 generate
      -i {{ .PAPERSPACE_OPENAPI_DIR }}/machines-only.json
      --skip-validate-spec
      -g typescript-axios
      -o {{ .PAPERSPACE_GENERATED_DIR }}

  release-prepare:
    cmd: ./hack/prepare-release.sh
  
  release-build-image:
    cmd: ./hack/build-release.sh

  