version: '3'

tasks:
  default:
    cmds:
    - task --list-all

  # Build and run a debug container from local source code
  # Example: task run-local -- list
  run-local:
    cmds:
    - docker build --progress=plain . -t crafteo/cloudypad:local &&  CLOUDYPAD_IMAGE="crafteo/cloudypad:local" ./cloudypad.sh {{.CLI_ARGS}}

  run-local-no-build:
    cmds:
    - CLOUDYPAD_IMAGE="crafteo/cloudypad:local" ./cloudypad.sh {{.CLI_ARGS}}

  #
  # Build and test
  #

  test-unit:
    cmds:
    - npx mocha --config test/unit/.mocharc.json ./test/unit --recursive

  build-local:
    cmds:
    - docker build -t crafteo/cloudypad:local .

  build-smoke-test:
    cmds:
    - task: build-local
    - docker run crafteo/cloudypad:local --version
    - >-
      [ $(docker run crafteo/cloudypad:local --version) = $(cat package.json | jq .version -r) ]  || echo "Version in container image doesn't match package.json version"

  test-create-and-destroy:
    cmds:
    - test/integ/create-and-destroy.sh

  # Detect potential circular deps with Madge
  test-circular-deps:
    cmds:
    - npx -y madge --ts-config ./tsconfig.json -c .

  #
  # Utils
  #

  mdbook-serve:
    dir: docs
    cmds:
    - mdbook serve

  # Generate Typescript Paperspace client from OpenAPI specifications
  paperspace-client-gen:
    vars:
      PAPERSPACE_OPENAPI_DIR: "src/providers/paperspace/client/openapi"
      PAPERSPACE_GENERATED_DIR: "src/providers/paperspace/client/generated-api"
    cmds:
    - curl https://api.paperspace.com/v1/openapi.json -o {{ .PAPERSPACE_OPENAPI_DIR }}/openapi.json

    # Filter only machine-related operations
    # Our client doesn't need the rest for now
    - >-
      cat {{ .PAPERSPACE_OPENAPI_DIR }}/openapi.json | jq '{ openapi, info, servers, components, externalDocs, paths: { 
        "/auth/session": .paths."/auth/session",
        "/public-ips": .paths."/public-ips",
        "/public-ips/{ip}": .paths."/public-ips/{ip}",
        "/machines": .paths."/machines",
        "/machines/{id}": .paths."/machines/{id}",
        "/machines/{id}/restart": .paths."/machines/{id}/restart",
        "/machines/{id}/start": .paths."/machines/{id}/start",
        "/machines/{id}/stop": .paths."/machines/{id}/stop",
      }}' > {{ .PAPERSPACE_OPENAPI_DIR }}/machines-only.json

    # # Cleanup old files before generation
    - rm -rf {{ .PAPERSPACE_GENERATED_DIR }} || true

    # Run generator
    - >-
      podman run -it --rm -v $PWD:/local -w /local docker.io/openapitools/openapi-generator-cli:latest@sha256:6747991566e4c3e43a30d5982f21da08c1cad78e95093fab04f494687b341788 generate -i {{ .PAPERSPACE_OPENAPI_DIR }}/machines-only.json --skip-validate-spec -g typescript-axios -o {{ .PAPERSPACE_GENERATED_DIR }}

  #
  # Release
  #

  release-create:
    cmds:
    - ./hack/release-create.sh
